; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 8MB
board_build.psram_type = qspi
upload_speed = 921600
monitor_speed = 115200
lib_deps =
	jgromes/RadioLib @ ^7.1.2
	mikalhart/TinyGPSPlus @ ^1.1.0
	lewisxhe/XPowersLib @ ^0.2.8
	olikraus/U8g2 @ ^2.35.30
	adafruit/Adafruit BME280 Library @ ^2.3.0
	adafruit/Adafruit Unified Sensor @ ^1.1.15

[env:tbeam-client]
extends = env
upload_port = COM7
monitor_port = COM7
build_flags =
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D ROLE_CLIENT

[env:tbeam-server]
extends = env
upload_port = COM8
monitor_port = COM8
build_flags =
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D ROLE_SERVER
