#!/usr/bin/env python3
"""Generate the offline Taiwan WMM2025 grid (no firmware build).

Generation only: pip install pygeomag==1.1.0
python tools/make_declination.py [--check]
NOAA WMM2025 is public domain. PyGeomag is an MIT-licensed port of NOAA's code.
Reference: https://www.ncei.noaa.gov/products/world-magnetic-model
Test values: https://www.ncei.noaa.gov/sites/default/files/2025-02/WMM2025_TEST_VALUES.txt
"""
import argparse
import hashlib
from importlib.metadata import version
from pathlib import Path

from pygeomag import GeoMag
from pygeomag.wmm.wmm_2025 import WMM_2025

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "include/taiwan_wmm_grid.h"
LAT_MIN, LAT_MAX, LON_MIN, LON_MAX = 18, 28, 116, 124
MODEL = GeoMag(coefficients_data=WMM_2025)


def declination(lat, lon, year, alt=0):
    return MODEL.calculate(glat=lat, glon=lon, alt=alt, time=year).d


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if version("pygeomag") != "1.1.0":
        raise SystemExit("Use pygeomag==1.1.0 for reproducible generation")
    # All 12 published NOAA declination test cases (rounded to 0.01 degree).
    expected = ((1.28, -0.16, 68.78), (0.85, -0.15, 68.21),
                (2.59, -0.24, 68.49), (2.16, -0.23, 67.93))
    for values, (year, alt) in zip(expected, ((2025, 0), (2025, 100),
                                             (2027.5, 0), (2027.5, 100))):
        for want, (lat, lon) in zip(values, ((80, 0), (0, 120), (-80, 240))):
            if abs(declination(lat, lon, year, alt) - want) > 0.0051:
                raise SystemExit("NOAA reference validation failed")
    values = []
    for lat in range(LAT_MIN, LAT_MAX + 1):
        for lon in range(LON_MIN, LON_MAX + 1):
            start, end = declination(lat, lon, 2025), declination(lat, lon, 2030)
            values.append((round(start * 1000), round((end - start) * 1000)))
    cols = LON_MAX - LON_MIN + 1

    def interpolate(lat, lon, year):
        row, col = min(int(lat - LAT_MIN), LAT_MAX - LAT_MIN - 1), min(int(lon - LON_MIN), cols - 2)
        fy, fx, time = lat - LAT_MIN - row, lon - LON_MIN - col, (year - 2025) / 5

        def at(r, c):
            base, delta = values[r * cols + c]
            return (base + delta * time) / 1000

        return ((at(row, col) * (1 - fx) + at(row, col + 1) * fx) * (1 - fy)
                + (at(row + 1, col) * (1 - fx) + at(row + 1, col + 1) * fx) * fy)

    worst = 0
    samples = 0
    for year in (2025, 2026.687, 2027.5, 2029.999):
        for y in range((LAT_MAX - LAT_MIN) * 4 + 1):
            for x in range((LON_MAX - LON_MIN) * 4 + 1):
                lat, lon = LAT_MIN + y / 4, LON_MIN + x / 4
                worst = max(worst, abs(interpolate(lat, lon, year) - declination(lat, lon, year)))
                samples += 1
    if worst > 0.02:
        raise SystemExit(f"Grid interpolation error too large: {worst:.6f} degrees")
    coefficient_hash = hashlib.sha256(repr(WMM_2025).encode("ascii")).hexdigest()
    lines = ["#pragma once", "#include <stdint.h>", "",
             "// Generated by tools/make_declination.py; do not edit by hand.",
             "// NOAA WMM2025, sea level; pygeomag 1.1.0; east-positive degrees.",
             f"// Coefficient tuple SHA256: {coefficient_hash}",
             f"// NOAA: 12 cases passed. Grid: {samples} samples, max error {worst:.6f} deg.",
             "namespace taiwan_wmm_grid {",
             f"constexpr int kLatMin = {LAT_MIN}, kLatMax = {LAT_MAX};",
             f"constexpr int kLonMin = {LON_MIN}, kLonMax = {LON_MAX};",
             f"constexpr int kRows = {LAT_MAX - LAT_MIN + 1}, kCols = {cols};",
             "// {2025 declination, change from 2025 to 2030}, in millidegrees.",
             "constexpr int16_t kValues[kRows * kCols][2] = {"]
    for row in range(LAT_MAX - LAT_MIN + 1):
        lines.append("  " + ", ".join("{%d, %d}" % v for v in values[row * cols:(row + 1) * cols]) + ",")
    lines += ["};", "}  // namespace taiwan_wmm_grid", ""]
    rendered = "\n".join(lines)
    if args.check:
        if OUTPUT.read_text() != rendered:
            raise SystemExit("Generated grid is stale; regenerate it")
    else:
        OUTPUT.write_text(rendered)
    print(f"NOAA 12/12 passed; grid {samples} samples; max interpolation error {worst:.6f} deg; {'unchanged' if args.check else 'generated'}")


if __name__ == "__main__":
    main()
